if db_id('MarketRace') is not null 
begin 
	use master 
	drop database MarketRace
end

create database MarketRace
go

USE MarketRace
go
CREATE TABLE ROLES(
  ID_RO     INT          PRIMARY KEY identity(1,1), 
  DESCRIPCION    VARCHAR(20)      NOT NULL UNIQUE
  )
  go
  

CREATE TABLE USUARIOS(
  ID_US      INT          PRIMARY KEY, 
  DNI   CHAR(8)      NOT NULL UNIQUE,
  NOMBRE    VARCHAR(50)  NOT NULL,
  APELLIDO    VARCHAR(50)  NOT NULL,
  TELEFONO  VARCHAR(10)  NOT NULL UNIQUE,
  DIRECCION VARCHAR(150) NOT NULL,
  CORREO VARCHAR(100) NOT NULL UNIQUE,
  CLAVE  VARCHAR(50)  NOT NULL UNIQUE,
  ID_RO	 	  INT		  NOT NULL,
  IMAGEN 	VARCHAR(1000) NOT NULL DEFAULT 'https://res.cloudinary.com/dfuuywyk9/image/upload/v1621437436/l60Hf_megote.png',
  FOREIGN KEY (ID_RO) REFERENCES ROLES (ID_RO)
)
go

CREATE TABLE MARCAS
(
    ID_MA       INT PRIMARY KEY identity(1,1),
    DESCRIPCION VARCHAR(30) NOT NULL UNIQUE,
    IMAGEN 	VARCHAR(1000) NOT NULL DEFAULT 'https://res.cloudinary.com/dfuuywyk9/image/upload/v1621437436/l60Hf_megote.png'
)
go

CREATE TABLE CATEGORIAS
(
    ID_CA       INT PRIMARY KEY identity(1,1),
    DESCRIPCION VARCHAR(30) NOT NULL UNIQUE,
    IMAGEN 	VARCHAR(1000) NOT NULL DEFAULT 'https://res.cloudinary.com/dfuuywyk9/image/upload/v1621437436/l60Hf_megote.png'
)
go

CREATE TABLE REPUESTOS
(
    ID_RE      INT PRIMARY KEY identity(1,1),
    SKU			VARCHAR(30)		NOT NULL UNIQUE,
    TITULO VARCHAR(100)  NOT NULL UNIQUE,
    DESCRIPCION VARCHAR(100)  NOT NULL UNIQUE,
    PRECIO      DECIMAL(6, 2) NOT NULL CHECK (PRECIO > 0),
    CANTIDAD    TINYINT       NOT NULL CHECK (CANTIDAD >= 0),
	IMAGEN 	VARCHAR(1000) NOT NULL DEFAULT 'https://res.cloudinary.com/dfuuywyk9/image/upload/v1621437436/l60Hf_megote.png',
    ID_MA       INT			NOT NULL,
    ID_CA       INT			NOT NULL,
    ESTADO       TINYINT     NOT NULL DEFAULT 1,
    FOREIGN KEY (ID_MA) REFERENCES MARCAS (ID_MA),
	FOREIGN KEY (ID_CA) REFERENCES CATEGORIAS (ID_CA)
)
go

CREATE TABLE DISTRITOS
(
    ID_DI  INT PRIMARY KEY identity(1,1),
    NOM VARCHAR(50) NOT NULL
)
go


CREATE TABLE DIRECCION_ENVIOS
(
    ID_EN       INT PRIMARY KEY identity(1,1),
    DIRECCION  VARCHAR(100) NOT NULL UNIQUE,
    REFERENCIA VARCHAR(100) NOT NULL,
    ID_DI 	INT NOT NULL,
    FOREIGN KEY (ID_DI) REFERENCES DISTRITOS (ID_DI)
)
go

CREATE TABLE ESTADO_COMPROBANTES(
  ID_ES     TINYINT          PRIMARY KEY identity(1,1), 
  DESCRIPCION    VARCHAR(20)      NOT NULL UNIQUE
)
go

CREATE TABLE COMPROBANTES
(
    ID_CO          INT 	   NOT NULL identity(1,1),
    ID_US         INT     NOT NULL,
    FECHA_PE       DATE    NOT NULL,
    CANTIDAD_TOTAL TINYINT NOT NULL CHECK (CANTIDAD_TOTAL >= 0),
    DESCUENTO  DECIMAL(6,2) NOT NULL,
    PRETOTAL DECIMAL(6,2) NOT NULL,
    ID_ES		   TINYINT NOT NULL ,
    ID_EN			INT     NOT NULL,
    PRIMARY KEY (ID_CO),
    FOREIGN KEY (ID_ES) REFERENCES ESTADO_COMPROBANTES (ID_ES),
    FOREIGN KEY (ID_EN) REFERENCES DIRECCION_ENVIOS (ID_EN),
    FOREIGN KEY (ID_US) REFERENCES USUARIOS (ID_US)
)
go


create TABLE DETALLE_COMPROBANTES
(
    ID_CO    INT           NOT NULL,
    ID_RE   INT           NOT NULL,
    PRECIO   DECIMAL(6, 2) NOT NULL CHECK (PRECIO > 0),
    CANTIDAD TINYINT       NOT NULL CHECK (CANTIDAD >0),
    IMPORTE  DECIMAL(6, 2) NOT NULL CHECK (IMPORTE > 0),
	FOREIGN KEY (ID_CO) REFERENCES COMPROBANTES(ID_CO),
    FOREIGN KEY (ID_RE) REFERENCES REPUESTOS (ID_RE)
)
go




INSERT INTO DISTRITOS(NOM) VALUES ('LIMA');
INSERT INTO DISTRITOS(NOM) VALUES ('ANCON');
INSERT INTO DISTRITOS(NOM)  VALUES ('ATE');
INSERT INTO DISTRITOS(NOM)  VALUES ('BARRANCO');
INSERT INTO DISTRITOS(NOM)  VALUES ('BREÑA');
INSERT INTO DISTRITOS(NOM)  VALUES ('CARABAYLLO');
INSERT INTO DISTRITOS(NOM)  VALUES ('CHACLACAYO');
INSERT INTO DISTRITOS(NOM)  VALUES ('CHORRILLOS');
INSERT INTO DISTRITOS(NOM)  VALUES ('CIENEGUILLA');
INSERT INTO DISTRITOS(NOM)  VALUES ('COMAS');
INSERT INTO DISTRITOS(NOM)  VALUES ('EL AGUSTINO');
INSERT INTO DISTRITOS(NOM)  VALUES ('INDEPENDENCIA');
INSERT INTO DISTRITOS(NOM)  VALUES ('JESUS MARIA');
INSERT INTO DISTRITOS(NOM)  VALUES ('LA MOLINA');
INSERT INTO DISTRITOS(NOM)  VALUES ('LA VICTORIA');
INSERT INTO DISTRITOS(NOM)  VALUES ('LINCE');
INSERT INTO DISTRITOS(NOM)  VALUES ('LOS OLIVOS');
INSERT INTO DISTRITOS(NOM)  VALUES ('LURIGANCHO');
INSERT INTO DISTRITOS(NOM)	VALUES ('LURIN');
INSERT INTO DISTRITOS(NOM)  VALUES ('MAGDALENA DEL MAR');
INSERT INTO DISTRITOS(NOM)  VALUES ('MAGDALENA VIEJA');
INSERT INTO DISTRITOS(NOM)  VALUES ('MIRAFLORES');
INSERT INTO DISTRITOS(NOM)  VALUES ('PACHACAMAC');
INSERT INTO DISTRITOS(NOM)  VALUES ('PUCUSANA');
INSERT INTO DISTRITOS(NOM)  VALUES ('PUENTE PIEDRA');
INSERT INTO DISTRITOS(NOM)  VALUES ('PUNTA HERMOSA');
INSERT INTO DISTRITOS(NOM)	VALUES ('PUNTA NEGRA');
INSERT INTO DISTRITOS(NOM)  VALUES ('RIMAC');
INSERT INTO DISTRITOS(NOM)  VALUES ('SAN BARTOLO');
INSERT INTO DISTRITOS(NOM)  VALUES ('SAN BORJA');
INSERT INTO DISTRITOS(NOM)  VALUES ('SAN ISIDRO');
INSERT INTO DISTRITOS(NOM)  VALUES ('SAN JUAN DE LURIGANCHO');
INSERT INTO DISTRITOS(NOM)  VALUES ('SAN JUAN DE MIRAFLORES');
INSERT INTO DISTRITOS(NOM)  VALUES ('SAN LUIS');
INSERT INTO DISTRITOS(NOM)  VALUES ('SAN MARTIN DE PORRES');
INSERT INTO DISTRITOS(NOM)  VALUES ('SAN MIGUEL');
INSERT INTO DISTRITOS(NOM)  VALUES ('SANTA ANITA');
INSERT INTO DISTRITOS(NOM)  VALUES ('SANTA MARIA DEL MAR');
INSERT INTO DISTRITOS(NOM)  VALUES ('SANTA ROSA');
INSERT INTO DISTRITOS(NOM)  VALUES ('SANTIAGO DE SURCO');
INSERT INTO DISTRITOS(NOM)  VALUES ('SURQUILLO');
INSERT INTO DISTRITOS(NOM)  VALUES ('VILLA EL SALVADOR');
INSERT INTO DISTRITOS(NOM)  VALUES ('VILLA MARIA DEL TRIUNFO');
go


/*Procedimiento Almacenado de Usuarios*/
create proc usp_listadoUsuario
as
begin
  select  ID_US, DNI , NOMBRE ,APELLIDO,TELEFONO,
  DIRECCION,CORREO, CLAVE,ID_RO,ID_ES 
  from USUARIOS
end 
go

/--------------------------------------/


create proc Lista_MARCAS
as
begin
  select ID_MA, DESCRIPCION 
    from MARCAS
end 
go

create proc Lista_CATEGORIAS
as
begin
  select ID_CA ,DESCRIPCION
  from CATEGORIAS
end 
go

create proc Lista_REPUESTOS
as
begin
  select ID_RE,SKU,TITULO,DESCRIPCION, PRECIO,CANTIDAD,
ID_MA,ID_CA,ID_ES  
from REPUESTOS
end 
go

create proc Lista_DISTRITOS
as
begin
  select ID_DI,NOM
    from DISTRITOS
end 
go

create proc Lista_DIRECCION_ENVIOS
as
begin
  select ID_EN,DIRECCION,REFERENCIA,ID_DI
    from DIRECCION_ENVIOS
end 
go

create proc Lista_ESTADO_COMPROBANTES
as
begin
  select ID_ES,DESCRIPCION
    from ESTADO_COMPROBANTES
end 
go

create proc Lista_COMPROBANTES
as
begin
  select ID_CO, ID_US,FECHA_PE,CANTIDAD_TOTAL,
    DESCUENTO, PRETOTAL,ID_ES,ID_EN	
    from COMPROBANTES
end 
go